[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Este valor es importante para el plugin de Next.js de Netlify
  # Debe establecerse en "false" para permitir rutas de API
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs" 