[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Descomenta esta sección si necesitas redirecciones API específicas
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/api/:splat"
#   status = 200

# Esta redirección es para manejar SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 